use_frameworks!

target 'DeviceLayout_Example' do
  pod 'DeviceLayout', :path => '../'

  target 'DeviceLayout_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
