use_frameworks!

target 'DeviceLayout_Example' do
  pod 'DeviceLayout', :path => '../'

  target 'DeviceLayout_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0'
    pod 'DeviceLayout', :path => '../'
  pod 'Nimble', '~> 5.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
